name: Bug Report
description: File a Bug Report
labels: [bug]
assignees:
  - "BeansBeefBroccoli"
body:
- type: markdown
  attributes:
    value: |
      Before submitting a bug report, please make sure that:
      - Your bug hasn't already been reported
      - You've filled out this form to the best of your ability
      - This issue has a descriptive title
- type: dropdown
  attributes:
    label: "Operating System(s)"
    multiple: true
    options:
    - "Windows"
    - "Linux"
    - "macOS"
    - "Other"
  validations:
    required: true
- type: input
  attributes:
    label: "LambdaCraft Version" # Mod Name
    placeholder: "Type Here"
  validations:
    required: true
- type: dropdown
  attributes:
    label: "Singleplayer or Multiplayer"
    options:
    - "Singleplayer"
    - "Multiplayer"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Description"
    placeholder: "Type Here"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Steps to Reproduce"
    placeholder: "Type Here"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Other Mods Involved"
    placeholder: "Type Here"
  validations:
    required: false
- type: textarea
  attributes:
    label: "Suspected Cause"
    placeholder: "Type Here"
  validations:
    required: false
- type: textarea
  attributes:
    label: "Log(s)"
    description: "**Don't** paste your logs here. Upload them to https://mclo.gs and link that here."
    placeholder: "Type Here"
  validations:
    required: false
